---

- set_fact:
    error_log_path: "{{mariadb_log_dir}}/{{mariadb_error_log}}"
    slow_log_path: "{{mariadb_log_dir}}/{{mariadb_slow_log}}"

- name: make log directory
  file:
    path: "{{mariadb_log_dir}}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755

- name: my.cnf
  template:
    src: "{{mariadb_cnf_template}}"
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart mariadb

- name: log rotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/mysql
    owner: root
    group: root
    mode: 0644

- name: create mysql data directory
  file:
    path: "{{mariadb_data_dir}}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755

- name: exec mysql_install_db
  command: sudo -u mysql mysql_install_db
  args:
    creates: "{{mariadb_data_dir}}/mysql"
  become: no

- include: selinux.yml

- name: start service
  service:
    name: mysql
    state: started
    enabled: yes
