---

- when: ansible_distribution == "CentOS"
  block:
    - when: ansible_distribution_major_version == "7"
      block:
        - when: ansible_architecture == "x86_64"
          set_fact:
            platform: "centos7-amd64"
    - when: ansible_distribution_major_version == "6"
      block:
        - when: ansible_architecture == "x86_64"
          set_fact:
            platform: "centos6-amd64"
        - when: ansible_architecture == "i386"
          set_fact:
            platform: "centos6-x86"
- when: ansible_distribution == "Amazon"
  block:
    - when: ansible_architecture == "x86_64"
      set_fact:
        platform: "centos6-amd64"
    - when: ansible_architecture == "i386"
      set_fact:
        platform: "centos6-x86"

- name: configure yum repository
  yum_repository:
    name: mariadb
    description: mariadb-{{mariadb_version}}
    baseurl: http://yum.mariadb.org/{{mariadb_version}}/{{platform}}
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    enabled: false

- name: install MariaDB
  yum:
    name: "{{item}}"
    enablerepo: mariadb
    update_cache: yes
    state: latest
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-devel
