---

- when: ansible_distribution == "CentOS"
  block:

  - name: install pip
    easy_install:
      name: pip

  - name: install mysql python package dependencies
    yum: name={{item}}
    with_items:
      - gcc
      - python-devel
      - zlib-devel
      - openssl-devel

  - name: install mysql python package
    pip:
      name: MySQL-python

- when: ansible_distribution == "Amazon"
  block:

  - name: install mysql python package
    yum:
      name: MySQL-python26
    when:
      - ansible_python.version.major == 2
      - ansible_python.version.minor == 6

  - name: install mysql python package
    yum:
      name: MySQL-python27
    when:
      - ansible_python.version.major == 2
      - ansible_python.version.minor == 7
