---

- name: create databases
  mysql_db:
    name: "{{item}}"
    login_unix_socket: "{{mariadb_socket_path}}"
  with_items:
    - "{{mariadb_databases}}"

- name: configure users
  include: user.yml
  with_items:
    - "{{mariadb_users}}"
  loop_control:
    loop_var: user
